### ISSUE TITLE
[3º Entrega] Doc. de Arquitetura de Software / Diagrama de Interação.

### ISSUE THREAD

**Issue by luludsf** [vonmoraes/lps-projeto#11]
- [x] 2. Diagramas de Interação.

> Adicionar o *Diagrama de Interação* ao [Doc. de Arquitetura de Software](https://github.com/vonmoraes/lps-projeto/blob/master/Documentos/doc_arquitetura.md).

> Template [Artifact:  Software Architecture Document](http://www.tesestec.com.br/pasteurjr/rup/process/artifact/ar_sadoc.htm).

**Comment by luludsf** [comment]
Diagrama de interação Moraes: 

Avaliar Ponto de Controle. 
![avaliar_ponto_de_controle](https://user-images.githubusercontent.com/26805177/56160489-b0123c00-5f9d-11e9-87ba-5a0064cca490.png)

Solicitar Orientador. 
![solicitar_orientador](https://user-images.githubusercontent.com/26805177/56160515-bb656780-5f9d-11e9-87be-ca7a9bc78096.png)

**Comment by luludsf** [comment]
Diagrama de Interação Alefe: 

Atribuir Nota de Coordenador. 
![AtribuiNotaCoordenador (SEQUENCIA)](https://user-images.githubusercontent.com/26805177/56160792-768e0080-5f9e-11e9-93a9-6a9404d19f28.png)

Submeter Ponto de Controle.
![SubmeterPC (SEQUENCIA)](https://user-images.githubusercontent.com/26805177/56160815-83125900-5f9e-11e9-903a-5858fdfe56aa.png)

**Comment by luludsf** [comment]
Diagrama de Interação Luana:

Login:
![login Sequencia](https://user-images.githubusercontent.com/26805177/56161343-a5f13d00-5f9f-11e9-9f19-54e046b76512.png)

Aceitar Solicitação Coordenador: 
![aceitarSolicitacaoCoordenador](https://user-images.githubusercontent.com/26805177/56161347-a8539700-5f9f-11e9-8036-17bfc32e4be9.png)

**Comment by vonmoraes** [comment]
Aceitar Solicitação de Orientador (Luana)



![AceitarSolicitacaoOrientadorSequencia](https://user-images.githubusercontent.com/31371849/56172275-1c516780-5fbf-11e9-88d4-89b1e60bb3db.png)

**Comment by vonmoraes** [comment]
Recuperar senha (Alefe) 
![RecuperarSenha Sequencia](https://user-images.githubusercontent.com/31371849/56172491-114b0700-5fc0-11e9-98b3-27882a46ada3.png)

**Comment by vonmoraes** [comment]
Diagrama de Interação Breno:
registrar
![Registrar_Usuario_Sequência](https://user-images.githubusercontent.com/31371849/56172639-bf56b100-5fc0-11e9-8f6e-80e0c3c88966.png)

ver e alterar dados cadastrais
![VA_Dados_Cadastrais_Sequência](https://user-images.githubusercontent.com/31371849/56172643-c251a180-5fc0-11e9-8d6d-e54bf09dae58.png)

**Comment by vonmoraes** [comment]
Aceitar Solicitação Orientando ( Breno) 

![AceitarSolicitaçãoOrientandoSequence](https://user-images.githubusercontent.com/31371849/56175175-49584700-5fcc-11e9-95a2-12be7cb71b4b.png)
