### ISSUE TITLE
[3º Entrega] Doc. de Arquitetura de Software / Diagramas de Componentes/Deployment.

### ISSUE THREAD

**Issue by luludsf** [vonmoraes/lps-projeto#12]
- [x] 3. Diagramas de Componentes/Deployment.

> Adicionar o *Diagrama de Componentes/Deplyment* ao [Doc. de Arquitetura de Software](https://github.com/vonmoraes/lps-projeto/blob/master/Documentos/doc_arquitetura.md).

> Template [Artifact:  Software Architecture Document](http://www.tesestec.com.br/pasteurjr/rup/process/artifact/ar_sadoc.htm).

**Comment by luludsf** [comment]
Diagrama de Componentes Alefe: 

Atribuir Nota Coordenador : 
![atribuir nota coordenador component](https://user-images.githubusercontent.com/26805177/56161046-02079180-5f9f-11e9-89a3-4e5f6aed57f5.png)

Submeter Ponto de Controle : 
![SubmeterPC (Component)](https://user-images.githubusercontent.com/26805177/56161074-0cc22680-5f9f-11e9-9d82-eb09bbb43298.png)

**Comment by vonmoraes** [comment]
Diagrama de Componentes Moraes:

Avaliar Ponto de Controle: 
![avaliar_ponto_controle_dcomponente](https://user-images.githubusercontent.com/31371849/56172090-4a827780-5fbe-11e9-9dcc-b16fc6e49100.png)

Solicitar Orientador: 

![solicitar_orientador_dcomponente](https://user-images.githubusercontent.com/31371849/56172095-4e15fe80-5fbe-11e9-9683-c91ede6b6480.png)

**Comment by vonmoraes** [comment]
Diagrama de Componentes Luana:

Efetuar login: 
![loginComponent](https://user-images.githubusercontent.com/31371849/56172218-c8df1980-5fbe-11e9-999a-f143758b2fab.png)
Aceitar Solicitação Coordenador: 
![AceitarSolicitacaoCoordenadorComponent](https://user-images.githubusercontent.com/31371849/56172229-d4324500-5fbe-11e9-833e-67fc8acce7fe.png)
Aceitar Solicitação Orientador: 
![AceitarSolicitacaoOrientador](https://user-images.githubusercontent.com/31371849/56172235-dbf1e980-5fbe-11e9-8c26-8586a5195437.png)

**Comment by vonmoraes** [comment]
Recuperar Senha (Alefe) 

![RecuperarSenha Component](https://user-images.githubusercontent.com/31371849/56172499-1dcf5f80-5fc0-11e9-9fd4-5068eb9e9508.png)

**Comment by vonmoraes** [comment]
Diagrama de Componentes Breno:
Registrar.
![Registrar Componente](https://user-images.githubusercontent.com/31371849/56172614-a5b56980-5fc0-11e9-9456-19ada3ddb1fd.png)

Ver e Alterar Dados Cadastrais. 
![Ver e alterar dados cadastrais componente](https://user-images.githubusercontent.com/31371849/56172599-93d3c680-5fc0-11e9-8a86-4a1f79e46e95.png)

**Comment by vonmoraes** [comment]
aceitar solicitação orientando ( breno ) 
![AceitarSoicitaçãoOrientandoComponent](https://user-images.githubusercontent.com/31371849/56175182-56753600-5fcc-11e9-85d8-b037c39c64aa.png)
