### ISSUE TITLE
[3º Entrega] Doc. de Arquitetura de Software / Diagrama de Classes de Projeto.

### ISSUE THREAD

**Issue by luludsf** [vonmoraes/lps-projeto#14]
- [x] 5. Diagrama de Classes de Projeto.

> Adicionar o *Diagrama de Classes de Projeto* ao [Doc. de Arquitetura de Software](https://github.com/vonmoraes/lps-projeto/blob/master/Documentos/doc_arquitetura.md).

> Template [Artifact:  Software Architecture Document](http://www.tesestec.com.br/pasteurjr/rup/process/artifact/ar_sadoc.htm).

**Comment by luludsf** [comment]
Diagrama de Classe de Projeto Moraes:

Avaliar Ponto de Controle.
![avaliar_ponto_de_controle](https://user-images.githubusercontent.com/26805177/56160617-01bac680-5f9e-11e9-9ee7-3043b6e33901.png)

Solicitar Orientador.
![solicitar_orientador](https://user-images.githubusercontent.com/26805177/56160622-07b0a780-5f9e-11e9-9bda-1090fc8ea08d.png)

**Comment by luludsf** [comment]
Diagrama de Classe de Projeto Alefe:

Atribuir Nota de Coordenador.
![AtribuiNotaCoordenador](https://user-images.githubusercontent.com/26805177/56160959-cc62a880-5f9e-11e9-8f5d-4234202ce8d7.png)


Submeter Ponto de Controle.
![SubmeterPC](https://user-images.githubusercontent.com/26805177/56160924-bd7bf600-5f9e-11e9-9ca1-5e5099ed3acd.png)

**Comment by luludsf** [comment]
Diagrama de Classe de Projeto Luana:

Login: 
![login classe](https://user-images.githubusercontent.com/26805177/56161226-66c2ec00-5f9f-11e9-8fa3-22cc49b86ec7.png)

Aceitar Solicitação coordenador: 
![Aceitar Solicitacao Coordenador](https://user-images.githubusercontent.com/26805177/56161237-6cb8cd00-5f9f-11e9-88ab-e51cedd8750e.png)

**Comment by vonmoraes** [comment]
Aceitar Solicitação de Orientador (Luana)

![AceitarSolicitacaoOrientadorClasse](https://user-images.githubusercontent.com/31371849/56172288-2e330a80-5fbf-11e9-9e3f-b28b82dc8acd.png)

**Comment by vonmoraes** [comment]
Recuperar Senha ( Alefe ) 
![RecuperarSenha Classe](https://user-images.githubusercontent.com/31371849/56172474-04c6ae80-5fc0-11e9-9b9c-ca655c8da774.png)

**Comment by vonmoraes** [comment]
Diagrama de Classe de Projeto Breno:

registrar

![Registrar Classe](https://user-images.githubusercontent.com/31371849/56172669-e614e780-5fc0-11e9-97c2-af3b749474e2.png)

ver e alterar  dados cadastrais
![Ver e alterar dados cadastrais Classe](https://user-images.githubusercontent.com/31371849/56172679-f0cf7c80-5fc0-11e9-99b2-1d5d4c3f97e4.png)

**Comment by vonmoraes** [comment]
Aceitar Solicitação Orientando ( Breno ) 
![AceitarSoicitaçãoOrientandoClass](https://user-images.githubusercontent.com/31371849/56175153-36457700-5fcc-11e9-9385-df5c962e871f.png)
