### ISSUE TITLE
[4º Entrega]  Doc. de Plano de Testes / Testes Funcionais.

### ISSUE THREAD

**Issue by vonmoraes** [vonmoraes/lps-projeto#18]
- [ ] 2. Casos de Testes Funcionais

**Comment by vonmoraes** [comment]
Template: 

### 2.1. Caso de Teste : Submeter Ponto de Controle

|                   Ações de Entrada/Eventos                   |                     Respostas Esperadas                      |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|              Aluno seleciona ponto de controle.              |       Abrir tela com o ponto de controle selecionado.        |
|       Aluno escreve a descrição do ponto de controle.        |                              NA                              |
| Aluno clica em submeter, e o ponto de controle é enviado ao sistema |    Recuperado pelo sistema os campos escritos pelo aluno.    |
|                              -                               | Ponto de controle é recebido pelo sistema e liberado para o orientador. |

**Comment by vonmoraes** [comment]
Pegar cada caso de uso no [doc especificação de requisitos](https://github.com/vonmoraes/lps-projeto/blob/master/Documentos/doc_especificacao_requisitos.md). Verificar a interação de cada caso de uso em conjunto com sua respectiva tela, escrever as **Respostas Esperadas** de cada **Ação de Entrada/Eventos**

**Comment by AlefeLucas** [comment]
### 2.2. Caso de Teste : Solicitar Orientador

|                   Ações de Entrada/Eventos                   |                     Respostas Esperadas                      |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|              Aluno clica em incluir orientador.              |       Exibir Lista de orientadores.        |
|       1- Aluno seleciona orientador da lista. <br> 2- Aluno clica em solicitar.        |                              Enviar solicitação de orientador ao orientador selecionado e exibir "solicitação enviada".                              |

**Comment by AlefeLucas** [comment]
### 2.3. Caso de Teste :  Atribuir nota de coordenador

|                   Ações de Entrada/Eventos                   |                     Respostas Esperadas                      |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|              Coordenador seleciona ponto de controle.              |       Abrir tela com o ponto de controle selecionado e lista de alunos que o enviaram.        |
|       Coordenador seleciona o aluno na lista de aluno.        |                              Exibir o ponto de controle desse aluno.                              |
| 1- Coordenador digita a nota do aluno<br> 2- Coordenador clica em submeter.  |   Atribuir a nota digitada ao ponto de controle do aluno selecionado.    |

**Comment by ICESchiess** [comment]
### 2.4.Aceitar solicitação de orientando.

|                   Ações de Entrada/Eventos                   |                     Respostas Esperadas                      |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|             Orientador clica na lista de requisições de orientando.              |       Exibir Lista de requisições.        |
|       Seleciona requição da lista      |  Exibe detalhes da requisição, bem como as opções de aceitar ou recusar                            |
| Orientador aceita ou rejeita requsição    |  Opção é salva no sistema, criando o vínculo caso necessário, e mandando mensagem para os envolvidos informando da decisão tomada   |

**Comment by ICESchiess** [comment]
### 2.5.Aceitar solicitação de orientador.

|                   Ações de Entrada/Eventos                   |                     Respostas Esperadas                      |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|             Coordenador clica na lista de requisições dos orientadores           |       Exibir Lista de requisições.        |
|       Seleciona requição da lista      |  Exibe detalhes da requisição, bem como as opções de aceitar ou recusar                            |
| Coordenador aceita ou rejeita requisição    |   Informação é salva no sistema, mandando mensagem para os envolvidos infrormando da decisão tomada.  |

**Comment by ICESchiess** [comment]
### 2.6. Recuperar Senha

|                   Ações de Entrada/Eventos                   |                     Respostas Esperadas                      |
| :----------------------------------------------------------: | :----------------------------------------------------------: |
|            Usuário clica na opção de recuperar senha          |       Sistema mostra mensagem pedindo para usuário informar seu endereço de e-mail, com respectivo campo para preenchimento    |
|      Usuário digita seu endereço de e-mail     |  Caso e-mail seja válido, sistema envia uma mensagem para o e-mail, informando a senha associada àquele e-mail. Caso contrário, sistema mostra uma mensagem falando que o e-mail é inválido, dando uma nova tentativa ao usuário.           |

**Comment by luludsf** [comment]
### 2.7. Caso de Teste : Efetuar Login

Ações de Entrada/Eventos | Respostas Esperadas
-- | --
Usuário entra com os dados (número de matrícula ou e-mail e senha). | NA
Usuário clica em entrar | A conta do usuário é verificada:  <br> 1 - Caso Usuário válido, libera o acesso ao sistema.   <br>       2 - Caso Usuário Aluno sem Orientador, é exibida em tela seu perfil para a seleção de um orientador.       <br>        3 - Caso Usuário Aluno com Orientador, é liberado acesso ao sistema.                                                               <br> 4 - Caso Usuário inválido, não libera o acesso ao sistema e sugere que o o usuário faça seu cadastro.

**Comment by luludsf** [comment]
### 2.8. Caso de Teste : Aceitar solicitação de coordenador 

| Ações de Entrada/Eventos                        | Respostas Esperadas                                          |
| ----------------------------------------------- | ------------------------------------------------------------ |
| Admin clica em vizualizar lista de solicitações | Lista de solicitações de admin é exibida.                    |
| Admin aceita/recusa a solicitação               | 1 - Caso solicitação aceita, sistema atualiza solicitação como aceita                                                                                                <br>   2 - Caso solicitação recusada, sistema atualiza solicitação como recusada |

**Comment by BrenoACos** [comment]
### 2.9. Caso de Teste : Visualizar/Alterar dados cadastrais

| Ações de Entrada/Eventos                        | Respostas Esperadas                                          |
-- | --
Usuário clica em visualizar dados | 1 - Verifica se usuário é aluno, orientador ou coordenador.<br> 2 - Apresenta as informações respectivas ao tipo de usuário.
Usuário clica em editar  | Mostra campos dos quais podem ser editados pelo tipo do usuário em questão.
Usuário preenche os campos e clica em confirmar|Informações preenchidas são alteradas no banco de dados

**Comment by BrenoACos** [comment]
### 2.10. Caso de Teste : Cadastrar-se

| Ações de Entrada/Eventos                        | Respostas Esperadas                                          |
| ----------------------------------------------- | ------------------------------------------------------------ |
| Usuário clica em cadastrar-se | Tela com campos cadastrais a serem preenchidos é apresentada |
| Usuário preenche campos e decide se deseja ser cadastrado como aluno ou orientador| Caso seja selecionado aluno, é enviado uma confirmação de email para o mesmo, caso seja registrado como orientador, é enviado uma confirmação para o coordenador|
