### ISSUE TITLE
[2º Entrega] Doc. de Especificação de Requisitos / Casos de Uso.

### ISSUE THREAD

**Issue by vonmoraes** [vonmoraes/lps-projeto#7]
3. Casos de Uso
    - [x] 3.1. Diagrama de Caso de Uso
    - [x] 3.2. Descrição de Caso de Uso

> Adicionar o *Diagrama de Caso de Uso* e escrever a *Descrição de Caso de Uso* no [Doc. Especificação de Requisitos](https://github.com/vonmoraes/lps-projeto/blob/master/Documentos/doc_especificacao_requisitos.md#documento-de-especifica%C3%A7%C3%A3o-de-requisitos).

> Template [Requirements Management Plan](http://www.tesestec.com.br/pasteurjr/rup/webtmpl/templates/req/rup_rmpln.htm).

**Comment by vonmoraes** [comment]
# Diagrama de caso de uso 
> Alterado 

![diagrama_de_caso_uso](https://user-images.githubusercontent.com/31371849/54547085-d2577080-4983-11e9-91dd-8866e029591c.png)

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Exemplo._
**Atores**: 
**Visão geral**: 
**Pré-requisitos**: 
**Pós-requisitos**: 

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Primeira coisa  | |
|                              |  2 - Segunda coisa |

**Fluxo alternativo**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Primeira coisa  | |
|                              |  2.1 - Segunda coisa |

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Submeter ponto de controle_.
**Atores**: Aluno
**Visão geral**: O aluno preenche o ponto de controle e o submete para avaliação.
**Pré-requisitos**: Aluno cadastrado.
**Pós-requisitos**: Ponto de controle submetido para o parecer do orientador. 

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Aluno seleciona data de fechamento do ponto de controle.  | |
| 2 - Aluno escreve a descrição do ponto de controle. | |
| 3 - Aluno clica em submeter, e o ponto de controle é enviado ao sistema | |
| | 4 - Ponto de controle é recebido pelo sistema e liberado para o orientador e coordenador. |

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Efetuar login._
**Atores**: Usuário.
**Visão geral**: Usuário cadastrado efetua login de acesso ao sistema.
**Pré-requisitos**: Usuário estar cadastrado. 
**Pós-requisitos**:  Usuário logado no sistema

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário digita número de matrícula ou e-mail e senha. | |
| 2 - Usuário clica em entrar. | |
| | 3 - Verifica a conta do usuário. |
| | 3.1 - Usuário válido, libera o acesso ao sistema.
| | 3.1.1 - Usuário Aluno sem Orientador, é exibida em tela seu perfil para a seleção de um orientador. |
| | 3.1.2 - Usuário Aluno com Orientador, é liberado acesso ao sistema.
| | 3.2 - Usuário inválido, não libera o acesso ao sistema e sugere que o o usuário faça seu cadastro. |

**Fluxo alternativo**: 1

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário clica em esqueceu a senha.| |
| 2 - Usuário digita número de matrícula ou e-mail. | |
| | 3 - Sistema envia e-mail com instruções de recuperação de senha. |

**Fluxo alternativo**: 2

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário clica em novo.| |
|  | 2 - Solicita o cadastro do usuário. |

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Avaliar ponto de controle._
**Atores**:  Orientador.
**Visão geral**:  Orientador visualiza e avalia o ponto de controle de seu orientando.
**Pré-requisitos**:  Orientador precisa estar logado no sistema.
**Pós-requisitos**:  Informações são salvas no sistema e ficam disponíveis para orientador, coordenador e aluno correspondente.
**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Orientador seleciona qual ponto de controle gostaria de visualizar.  | |
| |  2 - Sistema carrega o ponto de controle e o mostra na tela, bem como os campos "Nota" e "Parecer"  para o orientador preencher. |
| 3 - Orientador escreve o parecer.| |
| 4 - Orientador atribui nota de orientador ao ponto de controle. | |
| 5 - Orientador clica no botão "submeter" após preencher os campos. | |
|  | 6 - Verifica as informações escritas nos campos.  |
|  |  6.1 - Caso as informações estejam válidas, salva os dados no sistema e  encaminha para a coordenação. |
|  | 6.2 - Caso as informações estejam inválidas (nota maior que o máximo / campos vazios), uma mensagem é exibida ao usuário pedindo para verificar as informações. |

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Atribuir nota de coordenador._
**Atores**: Coordenador.
**Visão geral**: Coordenador visualiza um ponto de controle avaliado por um orientador. Após isso atribui sua nota ao ponto de controle do aluno. 
**Pré-requisitos**:  Coordenador estar cadastrado, parecer do ponto de controle submetido. 
**Pós-requisitos**: Nota de coordenador no ponto de controle alterada.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Seleciona ponto de controle a ser avaliado.  | |
| |  2 - Retorna ponto de controle escolhido. |
| 3 - Atribui nota ao ponto de controle. | |
| | 4 - Atualiza a nota de coordenador ao ponto de controle. |

**Comment by vonmoraes** [comment]
> 3- Orientador seleciona a ação que deseja realizar:
> - Escrever parecer
> - Atribuir nota do orientador
> - Encaminhar para coordenador

@ICESchiess Escrever parecer e atribuir nota do orientador ao ponto de controle são obrigatórios, ecaminhar para o coordenador é do sistema, quando o orientador clica em _**submeter**_ automáticamente já é encaminhado ao coordenador o parecer do orientador. 

Nota: arquivo = ponto de controle

**Comment by ICESchiess** [comment]
teste

**Comment by ICESchiess** [comment]
teste2

**Comment by vonmoraes** [comment]
?

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Escrever parecer_
**Atores**: Orientador
**Visão geral**:  Orientador escreve parecer sobre ponto de controle
**Pré-requisitos**: Orientador deve estar visualizando um ponto de controle, feito no caso de uso "Avaliar ponto de controle"
**Pós-requisitos**: Mensagem escrita está disponível para ser enviada e salva

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Orientador escreve um comentário na caixa de texto correspondente  | |
|                              |  2 - Mensagem fica disponível para ser salva e enviada (fica salva temporariamente na própria página) |

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Atribuir nota do orientador._
**Atores**: Orientador
**Visão geral**:  Orientador atribui nota para determinado ponto de controle
**Pré-requisitos**: Orientador deve estar visualizando um ponto de controle, feito no caso de uso "Avaliar ponto de controle"
**Pós-requisitos**: Nota está disponível para ser enviada e salva

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Orientador escreve uma nota na caixa de texto correspondente  | |
|                              |  2 - Nota fica disponível para ser salva e enviada (fica salva temporariamente na própria página) |
|  | 2.1 - Caso a nota escrita seja inválida, um ícone surge ao lado da caixa de texto para indicar que tem algo errado |

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Encaminhar para coordenação_
**Atores**: Orientador
**Visão geral**:  Sistema envia uma avaliação de um orientador feita em um ponto de controle ao coordenador responsável
**Pré-requisitos**: A validação feita no caso de uso "Avaliar ponto de controle" quando o botão "Submeter" é clicado deve ser positiva
**Pós-requisitos**:  Coordenador responsável recebe um um aviso da avaliação feita, bem como acesso à mesma

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
|  | 1 - Sistema envia ao coordenador responsável uma notificação sobre a avaliação feita, garantindo acesso de visualização à mesma|

**Comment by vonmoraes** [comment]
# Adicionar 
* Cadastrar 
*

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Cadastrar-se_
**Atores**: Usuário.
**Visão geral**: Cadastra um novo usuário ao sistema.
**Pré-requisitos**: -
**Pós-requisitos**: Usuário cadastrado.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário clica em cadastro. | |
| |  2 - Exibe tela de cadastro.|
| 3 - Usuário digita número de matrícula, e-mail e senha para cadastro. | |
| 4 - Usuário especifica o seu tipo de usuário, se ele é Aluno, Orientador ou Coordenador. | |
| 5 - Usuário clica na submissão de seus dados. | |
| | 6 - Sistema verifica as informações do usuário. |
| | 7. Exibe em tela mensagem "E-mail enviado para conclusão de cadastro!" |
| | 8. Salva informações do usuário. |

**Comment by vonmoraes** [comment]
# ADICIONAR 
- [x] Caso de uso: Visualizar perfil. (Usuário)
- [x] Caso de uso: Alterar dados cadastrais. (Usuário)
- [x] Caso de uso: Selecionar orientador. (Aluno)
- [x] Caso de uso: Recuperar senha. (Usuário)

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Recuperar senha._
**Atores**: Usuário.
**Visão geral**: Usuário recebe e-mail com sua senha.
**Pré-requisitos**: Usuário deve estar cadastrado no sistema.
**Pós-requisitos**: E-mail com senha enviada para o usuário.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário clica na opção de recuperar senha.  | |
|                              |  2 - Sistema mostra mensagem pedindo para usuário informar seu endereço de e-mail. |
| 3 - Usuário informa endereço de e-mail solicitado.  | |
|   | 4 - Sistema verifica endereço de e-mail informado.|
|   | 4.1 - Caso e-mail esteja cadastrado, sistema envia uma mensagem para o e-mail do usuário com sua senha.|
|   | 4.2 - Caso e-mail não esteja cadastrado, sistema mostra uma mensagem para o usuário e sugere tentar novamente.|

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Selecionar orientador_
**Atores**:  Aluno / Orientador
**Visão geral**:  Aluno seleciona seu orientador e este o aceita
**Pré-requisitos**:  Aluno e orientador devem estar cadastrados no sistema. Devem estar logados para realizar suas ações, mas um não depende do outro estar.
**Pós-requisitos**:  Aluno é atribuído a determinado orientador no sistema

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 -  Aluno seleciona seu orientador. | |
|                              |  2 - Sistema salva a requisição e envia uma mensagem ao orientador, pedindo confirmação. |
| 3 - Orientador confirma a requisição do aluno. | |
|  | 4- Sistema salva o "vínculo" e manda uma mensagem para o aluno avisando que sua requisição foi aprovada |

**Fluxo alternativo**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 3 - Orientador nega a requisição do aluno | |
|                              |  4 - Sistema salva a opção e manda uma mensagem para o aluno informando que seu pedido foi negado.|

**Comment by ICESchiess** [comment]
> Alterado para Visualizar/Alterar cadastro

#### Caso de Uso: _Visualizar perfil_
**Atores**: Usuário
**Visão geral**: Usuário tem acesso às suas informações cadastrais
**Pré-requisitos**:  Usuário deve estar cadastrado no sistema
**Pós-requisitos**:  Informações cadastrais estão sendo mostradas na tela

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário Efetuar Login | |
|                              |  2 - Sistema loga o usuário e mostra na tela a página inicial |
| 3 - Usuário seleciona a opção "Visualizar perifl" | |
|  | 4 - Sistema mostra na tela as informações cadastrais do usuário  |

**Comment by ICESchiess** [comment]
#### Caso de Uso: _Visualizar/Alterar dados cadastrais._
**Atores**: Usuário.
**Visão geral**: Usuário edita e altera seus dados cadastrais.
**Pré-requisitos**:  Usuário deve cadastrado no sistema.
**Pós-requisitos**:  Informações cadastrais são atualizadas no sistema.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Usuário Visualizar perfil.| |
|  2 - Usuário seleciona a opção de "Atualizar dados".                           |  |
|  | 3 - Sistema abre página com os campos possíveis de serem editados pelo usuário, já com a informação atual escrita. |
| 4 - Usuário altera os campos que deseja e clica no botão "Confirmar alterações".  |  |
|  | 5 - Sistema pede confirmação do usuário para salvar as alterações, através da escolha dentre dois botões "Sim" ou "Não". |
| 6 - Usuário escolhe "Sim". | |
| | 7 - Sistema verifica os dados. |
| | 7.1 - Se a verificação não apontou nada errado, sistema salva os dados e mostra uma mensagem de "Alteração realizada com sucesso". |
| | 7.2 - Se a verificação apontou erros (campo obrigatório em branco, _time_out_, etc), sistema exibe a mensagem com o erro e volta para a página anterior, sem alterar nenhum dado|

**Fluxo alternativo**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
|  6 - Usuário escolhe "Não". | |
|  | 7 - Sistema sai da página de atualização de dados sem salvar nenhuma alteração. |

**Comment by vonmoraes** [comment]
# ADICIONAR
- [x] Selecionar Orientador (Aluno)

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Solicitar Orientador._
**Atores**: Aluno.
**Visão geral**: Aluno seleciona seu orientador. 
**Pré-requisitos**: Aluno cadastrado e efetivado.
**Pós-requisitos**: Aluno com orientador. 

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Seleciona incluir ou alterar seu orientador.  | |
| |  2 - Exibe lista de orientadores. |
| 3 - Seleciona um orientador da lista. | |
| | 4 - Envia solicitação de orientador, ao orientador. |

**Comment by vonmoraes** [comment]
# ALTERAR

- [x] **Avaliar ponto de controle**: Escrever parecer, atribuir nota do orientador, encaminha para coordenação. 
- [x] **Selecionar Orientador**: Excluir 3º e 4º passo.  Alterar para solicitar orientador
- [x] **Alterar dados cadastrais**: Visualizar/Alterar dados cadastrais. 
- [x] **Atribuir nota do coordenador**: Atribuir nota de coordenador. 

# ADICIONAR

- [x] Aceitar solicitação de orientador.
- [x] Aceitar solicitação de coordenador. 
- [x] Aceitar solicitação de orientando aluno.

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Aceitar solicitação de orientando._
**Atores**: Orientador.
**Visão geral**: Orientador aceita solicitações de orientandos. 
**Pré-requisitos**: Orientador registrado, orientandos solicitando o orientador. 
**Pós-requisitos**: Orientando aceito ou negado.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Clica em visualizar lista de solicitações. | |
| |  2 - Exibe lista de solicitações do orientador. |
| 3 - Seleciona a solicitação.  | | 
| 4 - Seleciona opção aceitar solicitação. | |
| | 5 - Sistema atualiza solicitação como aceita. | 

**Fluxo alternativo**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Clica em visualizar lista de solicitações. | |
| |  2 - Exibe lista de solicitações do orientador. |
| 3 - Seleciona a solicitação.  | | 
| 4 - Seleciona opção negar solicitação. | |
| | 5 - Sistema atualiza solicitação como negada. |

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Aceitar solicitação de orientador._
**Atores**: Coordenador
**Visão geral**: Coordenador aceita solicitações de orientadores. 
**Pré-requisitos**: Coordenador registrado, orientador solicitando o coordenador. 
**Pós-requisitos**: Orientador aceito ou negado.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Clica em visualizar lista de solicitações. | |
| |  2 - Exibe lista de solicitações do coordenador. |
| 3 - Seleciona a solicitação.  | | 
| 4 - Seleciona opção aceitar solicitação. | |
| | 5 - Sistema atualiza solicitação como aceita. | 

**Fluxo alternativo**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Clica em visualizar lista de solicitações. | |
| |  2 - Exibe lista de solicitações do coordenador. |
| 3 - Seleciona a solicitação.  | | 
| 4 - Seleciona opção negar solicitação. | |
| | 5 - Sistema atualiza solicitação como negada. |

**Comment by vonmoraes** [comment]
#### Caso de Uso: _Aceitar solicitação de coordenador._
**Atores**: Admin.
**Visão geral**: Admin aceita solicitações de coordenadores. 
**Pré-requisitos**: Orientador solicitando o seu registro. 
**Pós-requisitos**: Orientador aceito ou negado.

**Fluxo de eventos**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Clica em visualizar lista de solicitações. | |
| |  2 - Exibe lista de solicitações do admin. |
| 3 - Seleciona a solicitação.  | | 
| 4 - Seleciona opção aceitar solicitação. | |
| | 5 - Sistema atualiza solicitação como aceita. | 

**Fluxo alternativo**:

| Ações do Ator | Respostas do Sistema |
|:-------------------:|:------------------------------:|
| 1 - Clica em visualizar lista de solicitações. | |
| |  2 - Exibe lista de solicitações do admin. |
| 3 - Seleciona a solicitação.  | | 
| 4 - Seleciona opção negar solicitação. | |
| | 5 - Sistema atualiza solicitação como negada. |

**Comment by vonmoraes** [comment]
# Enumeração dos casos de uso. 
- [x] 1. Submeter Ponto de Controle (Aluno)
- [x] 2. Solicitar Orientador (Aluno)
- [x] 3. Cadastrar-se (Usuário)
- [x] 4. Visualizar/Alterar Dados Cadastrais (Usuário)
- [x] 5. Efetuar Login (Usuário)
- [x] 6. Recuperar Senha (Usuário)
- [x] 7. Aceitar Solicitação de Orientador (Coordenador)
- [x] 8. Atribuir Nota de Coordenador (Coordenador)
- [x] 9. Avaliar Ponto de Controle (Orientador)
> - [x] Escrever Parecer
> - [x] Atribuir Nota de Orientador
> - [x] Encaminhar Para Coordenação
- [x] 10. Aceitar Solicitação de Orientando (Orientador)
- [x] 11. Aceitar Solicitação de Coordenador (Admin)
