### ISSUE TITLE
[2º Entrega] Doc. de Especificação de Requisitos / Prototipagem.

### ISSUE THREAD

**Issue by vonmoraes** [vonmoraes/lps-projeto#9]
- [x] 4. Prototipagem

> Adicionar imagens do *Protótipo* ao [Doc. Especificação de Requisitos](https://github.com/vonmoraes/lps-projeto/blob/master/Documentos/doc_especificacao_requisitos.md#documento-de-especifica%C3%A7%C3%A3o-de-requisitos).

> Template [Requirements Management Plan](http://www.tesestec.com.br/pasteurjr/rup/webtmpl/templates/req/rup_rmpln.htm).

**Comment by BrenoACos** [comment]
Tela 1 : Login
Tela 2 : Tela inicial de aluno
Tela 3 : Submeter ponto de controle (aluno)
Tela 4 : Avaliar ponto de controle (orientador)
Tela 5 : Atribuir nota de coordenador
Tela 7 : Tela inicial de orientador
Tela 8 : Tela inicial de coordenador
Tela 9 : Tela inicial de administrador
Tela 10 : Tela de recuperar senha
Tela 11 : Tela de minha conta (aluno)
Tela 12 : Tela de minha conta (coordenador e orientador)

[Untitled-screenshots.zip](https://github.com/vonmoraes/lps-projeto/files/2980826/Untitled-screenshots.zip)

**Comment by vonmoraes** [comment]
![1 1-Screen 1](https://user-images.githubusercontent.com/31371849/54569530-fc2b8a00-49b9-11e9-83fa-2b88ff9c3556.png)
> Tela 1

**Comment by vonmoraes** [comment]
![2 1-Screen 2](https://user-images.githubusercontent.com/31371849/54569542-05b4f200-49ba-11e9-9798-d63c5446e3ed.png)
> Tela 2

**Comment by vonmoraes** [comment]
![3 1-Screen 3](https://user-images.githubusercontent.com/31371849/54569556-0f3e5a00-49ba-11e9-809b-89a90a7d1255.png)
> Tela 3

**Comment by vonmoraes** [comment]
![4 1-Screen 4](https://user-images.githubusercontent.com/31371849/54569567-15ccd180-49ba-11e9-8427-77ecf22057d1.png)
> Tela 4

**Comment by vonmoraes** [comment]
![5 1-Screen 5](https://user-images.githubusercontent.com/31371849/54569575-1f563980-49ba-11e9-8ba1-e9d302ea80b4.png)
> Tela 5

**Comment by vonmoraes** [comment]
![6 1-Screen  7](https://user-images.githubusercontent.com/31371849/54569590-3137dc80-49ba-11e9-8c6e-e69e23bd7d09.png)
> Tela 6

**Comment by vonmoraes** [comment]
![7 1-Screen  8](https://user-images.githubusercontent.com/31371849/54569596-385eea80-49ba-11e9-9430-37331f4682bb.png)
> Tela 7

**Comment by vonmoraes** [comment]
![8 1-Screen  9](https://user-images.githubusercontent.com/31371849/54569609-4876ca00-49ba-11e9-9e0d-ad98038f9573.png)
> Tela 8

**Comment by vonmoraes** [comment]
![9 1-Screen 10](https://user-images.githubusercontent.com/31371849/54569615-50366e80-49ba-11e9-9a61-f429a21347a5.png)
> Tela 9

**Comment by vonmoraes** [comment]
![10 1-Screen 11](https://user-images.githubusercontent.com/31371849/54569628-56c4e600-49ba-11e9-9acc-c19cae1be8fc.png)
> Tela 10

**Comment by vonmoraes** [comment]
![11 1-Screen  12](https://user-images.githubusercontent.com/43856911/54569798-fa15fb00-49ba-11e9-954c-0f10ddd3934d.png)
> Tela 11
